# Generated by Django 3.2.1 on 2021-05-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_advisorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorProfile',
        ),
    ]
