# Generated by Django 3.2.1 on 2021-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
